[project]
name = "inference-track"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "nvidia-cuda-cccl>=13.3.3.4.1",
    "nvidia-cuda-nvcc>=13.3.73",
    "nvidia-cuda-runtime>=13.0.96",
    "vllm>=0.27",
]
