---
# Source: vllm-stack/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "vllm-router-service-account"
  namespace: vllm

---
# Source: vllm-stack/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "vllm-secrets"
  namespace: vllm
type: Opaque
data:

---
# Source: vllm-stack/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "vllm-qwen15b-storage-claim"
  namespace: vllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# Source: vllm-stack/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "vllm-reader"
  namespace: vllm
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch"]

---
# Source: vllm-stack/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-deployment-access-binding
  namespace: vllm
subjects:
  - kind: ServiceAccount
    name: vllm-router-service-account
    namespace: vllm
roleRef:
  kind: Role
  name: vllm-reader
  apiGroup: rbac.authorization.k8s.io

---
# Source: vllm-stack/templates/service-router.yaml
apiVersion: v1
kind: Service
metadata:
  name: "vllm-router-service"
  namespace: vllm
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: router
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: router
    release: router
spec:
  type: ClusterIP
  ports:
    - name: "router-sport"
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: "lmcache-port"
      port: 9000
      targetPort: lmcache-port
      protocol: TCP
    
  selector:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: router
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: router
    release: router

---
# Source: vllm-stack/templates/service-vllm.yaml
apiVersion: v1
kind: Service
metadata:
  name: "vllm-qwen15b-engine-service"
  namespace: vllm
  labels:
    app.kubernetes.io/name: qwen15b
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: serving-engine
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: test
    release: test
spec:
  type: ClusterIP
  ports:
    - name: "service-port"
      port: 80
      targetPort: "container-port"
      protocol: TCP
    - name: zmq-port
      port: 55555
      targetPort: zmq-port
      protocol: TCP
    - name: ucx-port
      port: 9999
      targetPort: ucx-port
      protocol: TCP
    
  selector:
    model: "qwen15b"
    helm-release-name: "vllm"
    app.kubernetes.io/name: qwen15b
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: serving-engine
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: test
    release: test

---
# Source: vllm-stack/templates/deployment-router.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "vllm-deployment-router"
  namespace: vllm
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: router
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: router
    release: router
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: router
      app.kubernetes.io/instance: vllm
      app.kubernetes.io/component: router
      app.kubernetes.io/part-of: vllm-stack
      app.kubernetes.io/managed-by: helm
      environment: router
      release: router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: router
        app.kubernetes.io/instance: vllm
        app.kubernetes.io/component: router
        app.kubernetes.io/part-of: vllm-stack
        app.kubernetes.io/managed-by: helm
        environment: router
        release: router
    spec:
      serviceAccountName: vllm-router-service-account
      containers:
      - name: router-container
        image: "lmcache/lmstack-router:latest"
        imagePullPolicy: "Always"
        env:
          - name: PYTHONHASHSEED
            value: "123"
          - name: LMCACHE_LOG_LEVEL
            value: "INFO"
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
          - "--service-discovery"
          - "k8s"
          - "--k8s-namespace"
          - "vllm"
          - "--k8s-service-discovery-type"
          - "pod-ip"
          - "--k8s-label-selector"
          - environment=test,release=test
          - "--routing-logic"
          - "roundrobin"
          - "--engine-stats-interval"
          - "15"
          - "--request-stats-window"
          - "60"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        ports:
          - name: "router-port"
            containerPort: 8000
          - name: "lmcache-port"
            containerPort: 9000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: router-port
          initialDelaySeconds: 30
          periodSeconds: 5
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: router-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: router-port
          initialDelaySeconds: 30
          periodSeconds: 5

---
# Source: vllm-stack/templates/deployment-vllm-multi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "vllm-qwen15b-deployment-vllm"
  namespace: vllm
  labels:
    model: qwen15b
    helm-release-name: vllm
    app.kubernetes.io/name: qwen15b
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/component: serving-engine
    app.kubernetes.io/part-of: vllm-stack
    app.kubernetes.io/managed-by: helm
    environment: test
    release: test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      model: qwen15b
      helm-release-name: vllm
      app.kubernetes.io/name: qwen15b
      app.kubernetes.io/instance: vllm
      app.kubernetes.io/component: serving-engine
      app.kubernetes.io/part-of: vllm-stack
      app.kubernetes.io/managed-by: helm
      environment: test
      release: test
  progressDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        model: qwen15b
        helm-release-name: vllm
        app.kubernetes.io/name: qwen15b
        app.kubernetes.io/instance: vllm
        app.kubernetes.io/component: serving-engine
        app.kubernetes.io/part-of: vllm-stack
        app.kubernetes.io/managed-by: helm
        environment: test
        release: test
    spec:
      hostname: "vllm-qwen15b-vllm-stack"
      subdomain: "vllm-qwen15b-engine-service"
      containers:
        - name: "vllm"
          image: "vllm/vllm-openai:v0.30.0"
          securityContext:
            runAsNonRoot: false
          command:
          - "vllm"
          - "serve"
          - "Qwen/Qwen2.5-1.5B-Instruct"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "8000"
          - "--no-enable-prefix-caching"
          - "--max-model-len"
          - "4096"
          - "--dtype"
          - "bfloat16"
          - "--gpu_memory_utilization"
          - "0.85"
          imagePullPolicy: "Always"
          env:
          - name: PYTHONHASHSEED
            value: "123"
          - name: HF_HOME
            value: /data
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PROMETHEUS_MULTIPROC_DIR
            value: "/tmp"
          ports:
            - name: "container-port"
              containerPort: 8000
            - name: zmq-port
              containerPort: 55555
            - name: ucx-port
              containerPort: 9999          
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 60
            httpGet:
              path:  /health
              port: 8000
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path:  /health
              port: 8000
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
            httpGet:
              path:  /health
              port: 8000
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
          - name: vllm-storage
            mountPath: /data
      volumes:
        - name: vllm-storage
          persistentVolumeClaim:
            claimName: "vllm-qwen15b-storage-claim"
      runtimeClassName: nvidia
